In [27]:
import numpy as np
from importlib import reload
import par_from_Ed_380_412_443_490_555_v5  # Import the module first
reload(par_from_Ed_380_412_443_490_555_v5)  # Force reload
from par_from_Ed_380_412_443_490_555_v5 import PAR_from_Ed_380_412_443_490_555_v5

# Test data
Ed = np.array([[0.10728,0.27631,0.37879,0.50215,0.25799],
         [4.7654e-06,3.9603e-05,0.00020864,0.00067752,3.2299e-06],
         [6.0923e-05,0.00032247,0.0014818,0.006675,0.0016808]])
z = np.array([18.1,155.3,71.1])

PAR, PAR_b, ep50, IQR_ep = PAR_from_Ed_380_412_443_490_555_v5(Ed, z)

print(PAR)

[2.64150639e+02 1.47233679e-01 2.09328181e+00]


In [26]:
import numpy as np
from importlib import reload
import par_from_Ed_380_490_555_665_v5  # Import the module first
reload(par_from_Ed_380_490_555_665_v5)  # Force reload
from par_from_Ed_380_490_555_665_v5 import PAR_from_Ed_380_490_555_665_v5

# Test data
Ed = np.array([[0.72199,1.6553,1.6139,1.0218],
    [0.0021873,0.062225,0.0052865,1.7514e-05],
    [0.079935,0.45121,0.32895,0.0012265]])
z = np.array([0.7,74.4,16.4])

PAR, PAR_b, ep50, IQR_ep = PAR_from_Ed_380_490_555_665_v5(Ed, z)

print(PAR)

[1847.8348424    19.24115742  266.79539862]


In [25]:
import numpy as np
from importlib import reload
import par_from_Ed_380_412_490_v5  # Import the module first
reload(par_from_Ed_380_412_490_v5)  # Force reload
from par_from_Ed_380_412_490_v5 import PAR_from_Ed_380_412_490_v5

# Test data
Ed = np.array([[0.00026646,0.0017325,0.01242],
    [0.0040838,0.017985,0.027024],
    [3.928e-05,0.00033364,0.0033945]])
z = np.array([43.1,119.7,137.8])

PAR, PAR_b, ep50, IQR_ep = PAR_from_Ed_380_412_490_v5(Ed, z)

print(PAR)

[3.80900363 9.36829809 0.8741716 ]


In [24]:
import numpy as np
from importlib import reload
import par_from_Ed_380_443_490_555_v5  # Import the module first
reload(par_from_Ed_380_443_490_555_v5)  # Force reload
from par_from_Ed_380_443_490_555_v5 import PAR_from_Ed_380_443_490_555_v5

# Test data
Ed = np.array([[3.1477e-07,4.401e-05,0.00031093,2.6219e-05],
        [0.0097528,0.061085,0.10562,0.087316],
        [0.20572,0.52315,0.54544,0.16185]
])
z = np.array([84.8,14.2,28.1])

PAR, PAR_b, ep50, IQR_ep = PAR_from_Ed_380_443_490_555_v5(Ed, z)

print(PAR)

[7.31593367e-02 6.21694623e+01 2.74837298e+02]


In [23]:
import numpy as np
from importlib import reload
import par_from_Ed_380_443_490_560_v5  # Import the module first
reload(par_from_Ed_380_443_490_560_v5)  # Force reload
from par_from_Ed_380_443_490_560_v5 import PAR_from_Ed_380_443_490_560_v5

# Test data
Ed = np.array([[3.1477e-07,4.401e-05,0.00031093,2.6219e-05],
        [0.0097528,0.061085,0.10562,0.087316],
        [0.20572,0.52315,0.54544,0.16185]
])
z = np.array([84.8,14.2,28.1])

PAR, PAR_b, ep50, IQR_ep = PAR_from_Ed_380_443_490_560_v5(Ed, z)

print(PAR)

[7.67706608e-02 6.39371514e+01 2.79949340e+02]
